-- Create tables for Supabase Database

-- 1. Hero Table
CREATE TABLE IF NOT EXISTS public.hero (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name TEXT,
    last_name TEXT,
    display_name TEXT,
    nickname TEXT,
    birth_date TEXT,
    start_date TEXT,
    location TEXT,
    profile_image TEXT,
    emoji TEXT,
    webring_url TEXT,
    positions JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. About Me Table
CREATE TABLE IF NOT EXISTS public.about_me (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nickname TEXT,
    status TEXT,
    status_link TEXT,
    full_name TEXT,
    birthday TEXT,
    location TEXT,
    facts JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. Tech Stack Table
CREATE TABLE IF NOT EXISTS public.tech_stack (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category TEXT NOT NULL,
    "order" INT DEFAULT 0,
    technologies JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. Contact Table
CREATE TABLE IF NOT EXISTS public.contact (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email TEXT,
    socials JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 5. Blog Table
CREATE TABLE IF NOT EXISTS public.blog (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    image TEXT,
    date TEXT,
    content TEXT,
    published BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Enable Row Level Security (RLS) & Public Read Policies
ALTER TABLE public.hero ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.about_me ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tech_stack ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blog ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read hero" ON public.hero FOR SELECT USING (true);
CREATE POLICY "Allow public read about_me" ON public.about_me FOR SELECT USING (true);
CREATE POLICY "Allow public read tech_stack" ON public.tech_stack FOR SELECT USING (true);
CREATE POLICY "Allow public read contact" ON public.contact FOR SELECT USING (true);
CREATE POLICY "Allow public read blog" ON public.blog FOR SELECT USING (true);
